const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
  };
  
export const UPDATE_SHOP_COLLECTIONS = "UPDATE_SHOP_COLLECTIONS";
export const UPDATE_SHOP_COLLECTIONS_API_SUCCESS = "UPDATE_SHOP_COLLECTIONS_API_SUCCESS";
export const UPDATE_SHOP_COLLECTIONS_API_FAILURE = "UPDATE_SHOP_COLLECTIONS_API_FAILURE";
export const UPDATE_SHOP_COLLECTIONS_API_START = "UPDATE_SHOP_COLLECTIONS_API_START";
export default ShopActionTypes;
